version: '3.7'

services:
  dev_rabbitmq:
    image: rabbitmq:3-management
    container_name: mssqlrr_rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/mnesia
  dev_redis:
    image: redis
    container_name: mssqlrr_redis
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  
    volumes:
      - redis_data_volume:/data
  
  dev_mssql:
    image: microsoft/mssql-server-linux
    container_name: mssqlrr_mssql
    environment:
            SA_PASSWORD: "MsSql!2019?"
            ACCEPT_EULA: "Y"
    restart: on-failure
    ports:
      - "1433:1433"
    volumes:
      - mssql_data_volume:/var/opt/mssql/
volumes:
  rabbitmq_data_volume:
  redis_data_volume:
  mssql_data_volume:
